// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC4jFnWLOLwm-gMjXn30Ql8WJJbk5cPAAQ',
    appId: '1:292917114766:web:d7b6daafedd9effb9d96df',
    messagingSenderId: '292917114766',
    projectId: 'nasihat-mama',
    authDomain: 'nasihat-mama.firebaseapp.com',
    storageBucket: 'nasihat-mama.appspot.com',
    measurementId: 'G-VVJE30S49S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDtFl8UZs5g5WZ6ktl-5tuS0ol09Ny2STk',
    appId: '1:292917114766:android:1132e6f1407365789d96df',
    messagingSenderId: '292917114766',
    projectId: 'nasihat-mama',
    storageBucket: 'nasihat-mama.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAnAxWoLPRmFbgggyuxS1iLIKJpZicr87M',
    appId: '1:292917114766:ios:1efa7c3055f8f9439d96df',
    messagingSenderId: '292917114766',
    projectId: 'nasihat-mama',
    storageBucket: 'nasihat-mama.appspot.com',
    iosClientId:
        '292917114766-h4ijmugik9kobjidgbo9fsbenhb2a3i0.apps.googleusercontent.com',
    iosBundleId: 'dev.mtsstudio.nasihatMama',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAnAxWoLPRmFbgggyuxS1iLIKJpZicr87M',
    appId: '1:292917114766:ios:1efa7c3055f8f9439d96df',
    messagingSenderId: '292917114766',
    projectId: 'nasihat-mama',
    storageBucket: 'nasihat-mama.appspot.com',
    iosClientId:
        '292917114766-h4ijmugik9kobjidgbo9fsbenhb2a3i0.apps.googleusercontent.com',
    iosBundleId: 'dev.mtsstudio.nasihatMama',
  );
}
